### ISSUE TITLE
Mismatch in the size of Video and Position data

### ISSUE THREAD

**Issue by ttngu207** [SainsburyWellcomeCentre/aeon_mecha#130]
There are cases where the loaded Video data and Position data for the same time period are having different size.

For example, for experiment 0.2

```
root = '/ceph/aeon/aeon/data/raw/AEON2/experiment0.2'
start='2022-05-04 22:00:00'
end='2022-05-04 23:00:00'
```

Loading the Video from `CameraTop` will returns a DataFrame with ***175725*** rows, where as Position will return ***175104*** rows. 

```
from aeon.schema import dataset as aeon_schema
from aeon.io import api as io_api


device_schema = aeon_schema.exp02
device = device_schema.CameraTop

positiondata = io_api.load(
    root=root,
    reader=device.Position,
    start=pd.Timestamp(start),
    end=pd.Timestamp(end))

videodata = io_api.load(
    root=root,
    reader=device.Video,
    start=pd.Timestamp(start),
    end=pd.Timestamp(end))

```

**Comment by glopesdev** [comment]
@ttngu207 this seems to be a symptom of a wider problem with that entire chunk. I was looking through the raw data and essentially all the data streams from this particular chunk have been affected and are missing around 2 min of data at the end. This includes not just the video data from CameraTop but all other data streams, for example wheel encoder data from Patch1 and Patch2, etc.

This to me strongly indicates that the origin of the problem might have been in the transfer of data between the acquisition computer and CEPH. Here there are a few scenarios to explore, including network transfer failure, robocopy script failure, unforeseen consequences of the recent data relocation (although this one shouldn't affect a chunk selectively unless the relocation was done around this exact time and there was some kind of race condition competing for resources? need to check notes).

Comparing notes on what was happening with the different data stores around this date and time might help us to understand the problem, and in any case we probably should keep this issue open and maybe even broaden its scope to help us think of ways to avoid a similar problem in the future.

It doesn't seem like subsequent data was affected, so we probably should also think of ways of validating and discarding either this chunk or the tail of the chunk from the minimum common timestamp in all data streams so we can unblock loading and ingestion of chunks like these.

**Comment by glopesdev** [comment]
@lochhh can you maybe post here other examples of mismatches that you found so I can investigate those cases further to see if they also follow this pattern?

**Comment by glopesdev** [comment]
@lochhh thanks for posting these. The good news is that all these datasets seem to be consistent from a hardware acquisition perspective. Looking at the raw data, all of them seem to fall either at the start or the end of acquisition epochs. In these particular chunks it makes sense that the total number of frames is different from other chunks since the recording lasts for less than one hour (due to the missing data before the system was started, or after it has stopped).

We decided to allow for this in case it is necessary to restart the acquisition system due to unforeseen circumstances. In these situations it is also possible to have overlapping chunks across different acquisition epochs if the system was rebooted within the same hour. All data timestamps should still be monotonic increasing, but there might be gaps or a smaller number of data points from the period when the system was down.

```
root = '/ceph/aeon/aeon/data/raw/AEON2/experiment0.2'

# 166873 pos rows; 166874 vid rows
start='2022-06-06 07:00:00'
end='2022-06-06 08:00:00'
```

Strangely, when I ran this first example through my notebook, the pos and vid rows seem to be matching in length, with 167260 rows each which is larger than both the pos and vid rows you observed. We should double-check the results together to make sure I'm loading the right chunk. If there is indeed a mismatch we could be in the presence of another instance of the data transfer issue above.

@ttngu207 @lochhh let's discuss at next meeting whether these overlapping chunks are a problem for the data ingestion routines for position data and we can figure out ways to merge or interpolate across these.

**Comment by jkbhagatio** [comment]
I believe this was related to stuttering issues of the old threadripper cpu acquisition machines. Please re-open with an explanation if not
