### ISSUE TITLE
Error with aeon.io.reader.Video 

### ISSUE THREAD

**Issue by JaerongA** [SainsburyWellcomeCentre/aeon_mecha#219]
`aeon.io.reader.Video` cannot extract video frames since this [pr ](https://github.com/SainsburyWellcomeCentre/aeon_mecha/pull/217/files#diff-9e12006926fd7f380f74726c41d2b41e2f1c99ce2a0d980c1df1a435b320ff73R120)has been merged.  

The error comes from this line:

https://github.com/SainsburyWellcomeCentre/aeon_mecha/blob/d52a44f2275fadb29bd024b56e00a837b9c2669f/aeon/io/api.py#L79

where previously it was 

```
for fname in Path(path).glob(f"{epoch_pattern}/**/{reader.pattern}*.{reader.extension}")}
```
For example, the following code returns zero.

```
import pathlib
import datetime
from aeon.io import api as io_api
from aeon.io import reader as io_reader

camera_name = "CameraTop"
start_time = datetime.datetime(2022, 4, 3, 6, 0, 0)
end_time = datetime.datetime(2022, 4, 3, 15, 0, 0)
raw_data_dir = pathlib.Path("/ceph/aeon/aeon/data/raw/AEON2/experiment0.2")
experiment_name = "exp0.2-r0"


videodata = io_api.load(
    root=raw_data_dir.as_posix(),
    reader=io_reader.Video(camera_name),
    start=pd.Timestamp(start_time),
    end=pd.Timestamp(end_time),
)

len(videodata)
```

**Comment by glopesdev** [comment]
@JaerongA indeed this was an internal breaking behavior change introduced to resolve #145. A more extensive discussion of the tradeoffs is included in that issue, but basically removing the wildcard was done to lift the assumption that all files in the dataset are chunked. Some files may be singleton, non-chunked files such as the Metadata or other session specific files.

We also discuss there the explicit workaround we are using in all our metadata schemas so that the high-level analysis code doesn't break: https://github.com/SainsburyWellcomeCentre/aeon_mecha/blob/main/aeon/schema/core.py#L4-L6

I think you are seeing this here because you are using the unprotected low-level `Video` reader directly. In this case you can get back the correct behavior by appending the required wildcard prefix to the end of the camera pattern:

```python
videodata = aeon.load(
    root=raw_data_dir.as_posix(),
    reader=Video(f'{camera_name}_*'),
    start=pd.Timestamp(start_time),
    end=pd.Timestamp(end_time),
)

len(videodata)
```

**Comment by JaerongA** [comment]
Thanks, @glopesdev. It's working with the code above.
