### ISSUE TITLE
Standardize 'aeon' imports

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_mecha#238]
Different people are using different imports for common aeon modules - these imports should be standardized for readability, similar to how people typically use standard imports for other packages (e.g. `import pandas as pd` and `import numpy as np`).

One thing that should be avoided is shadow imports: e.g. I've seen the pattern `import aeon.io.api as aeon` which is bad because it shadows the entire 'aeon' package.

**Comment by glopesdev** [comment]
I think this happened due to an organic evolution from the humble origins of the package when there was only a single-file `aeon` module. The fractioning came from splitting features into multiple sub-modules and folders.

This makes sense from a development perspective, but not entirely sure we should use it directly for high-level usage. For example, I would like to preserve the syntax `aeon.load` as standard, similar to pandas and numpy `np.genfromtxt` or `pd.read_csv`. I'm not completely familiar with how numpy and pandas do it, but suspect this would entail using `__init__.py` files to bring multiple sub-modules under a single namespace.

Currently as it is the `aeon` namespace itself is totally empty, and I think it might make it easier to step into the library if that module / namespace was the natural entry point, rather than having to immediately choose from a complex sub-module hierarchy.

**Comment by jkbhagatio** [comment]
>  I would like to preserve the syntax aeon.load as standard, similar to pandas and numpy np.genfromtxt or pd.read_csv

Sure, yup we can do this, yes it involves setting the '__init__.py' files properly. In this case, the call function would look like this:
```
import aeon
data = aeon.load(...)
```

This is a fine solution as it avoids the shadowing problem, and we can make it a standard and discuss what other functions we may want accessible in this way.
